### PR TITLE
Add mypy checks

### PR DESCRIPTION
**Pull request by RLKRo**
As mentioned [here](https://github.com/deeppavlov/dialog_flow_framework/pull/2#issuecomment-1285148775) viewing codestyle check results is not convenient.

This pull request solves that problem in two ways:

1. [codestyle1.yml](https://github.com/deeppavlov/dialog_flow_framework/blob/codestyle/add-mypy-check/.github/workflows/codestyle1.yml) -- produces the following [output](https://github.com/deeppavlov/dialog_flow_framework/actions/runs/3288209718).
2. [codestyle2.yml](https://github.com/deeppavlov/dialog_flow_framework/blob/codestyle/add-mypy-check/.github/workflows/codestyle2.yml) -- produces the following [output](https://github.com/deeppavlov/dialog_flow_framework/actions/runs/3288209744).

In my opinion, the second solution is better.

### CODE REVIEW

**Comment by pseusys** [comment]
Второй вариант, конечно, нагляднее. Но:
1. Требует checkout, и установления зависимостей трижды (долго).
2. В принципе какая разница, если все чеки все равно должны проходить.  
Поэтому предлагаю либо оставить первый либо рассмотреть второй с использованием кеширования зависимостей (возможно, слишком сложно).

**Comment by kudep** [comment]
Second option is faster then our current unit-tests (because of that we  do not have to wait three linting tests) and it's more atomic style. So I prefer the second one.

**Review by kudep — APPROVED** [review]

**Comment by kudep** [comment]
We will wait until the end of addon's mega-merges.

**Review by pseusys — APPROVED** [review]

**Comment by kudep** [comment]
Do we need this PR, i think it can be closed

**Comment by RLKRo** [comment]
I think it should be used to add mypy check. The name of the branch is `codestyle/add-mypy-check`. So should probably just rename this PR.

**Pull request closed without merging**
